services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: invest
      POSTGRES_USER: invest
      POSTGRES_PASSWORD: invest
    volumes:
      - invest-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://invest:invest@db:5432/invest
      JWT_SECRET: changeme
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  invest-db:
